# Generated by Django 5.1.7 on 2025-05-19 08:58

import charivol.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_name', models.CharField(max_length=100)),
                ('area_province', models.CharField(max_length=50)),
                ('area_city', models.CharField(max_length=50)),
                ('area_postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('area_address', models.TextField()),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Donation Area',
                'db_table': 'charivol_donation_areas',
            },
        ),
        migrations.CreateModel(
            name='Donor',
            fields=[
                ('id', models.CharField(default=charivol.models.generate_unique_id, editable=False, max_length=25, primary_key=True, serialize=False, unique=True)),
                ('contact', models.CharField(max_length=20)),
                ('province', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('address', models.TextField(max_length=255)),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Laki-laki'), ('Female', 'Perempuan')], max_length=10, null=True)),
                ('occupation', models.CharField(blank=True, max_length=40, null=True)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donatur', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donatur',
                'db_table': 'charivol_donaturs',
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.CharField(default=charivol.models.generate_unique_id, editable=False, max_length=25, primary_key=True, serialize=False, unique=True)),
                ('donation_name', models.CharField(choices=[('CLOTHING', 'Pakaian'), ('FOOD', 'Makanan'), ('STATIONERY', 'Alat Tulis'), ('BOOK', 'Buku'), ('TOY', 'Mainan'), ('FOOTWEAR', 'Sepatu'), ('FURNITURE', 'Perabotan'), ('OTHER', 'Lainnya')], default='FOOD', max_length=40)),
                ('image_url', models.URLField()),
                ('collection_location', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('PENDING', 'Menunggu Konfirmasi'), ('ACCEPTED', 'Diterima'), ('REJECTED', 'Ditolak')], default='PENDING', max_length=20)),
                ('donation_date', models.DateField(auto_now_add=True)),
                ('admin_remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('volunteer_remarks', models.CharField(blank=True, max_length=100, null=True)),
                ('updation_date', models.DateField(null=True)),
                ('donation_area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='charivol.donationarea')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charivol.donor')),
            ],
            options={
                'verbose_name': 'Donation',
                'db_table': 'charivol_donations',
            },
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_picture_url', models.URLField(blank=True, null=True)),
                ('caption', models.CharField(blank=True, max_length=255, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('donation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charivol.donation')),
            ],
            options={
                'verbose_name': 'Gallery',
                'db_table': 'charivol_gallery',
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.CharField(default=charivol.models.generate_unique_id, editable=False, max_length=25, primary_key=True, serialize=False, unique=True)),
                ('province', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('contact', models.CharField(max_length=20)),
                ('address', models.TextField()),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Laki-laki'), ('Female', 'Perempuan')], max_length=10, null=True)),
                ('photo_url', models.URLField(blank=True, null=True)),
                ('id_picture', models.ImageField(blank=True, null=True, upload_to='volunteer/id_pictures')),
                ('about_me', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=20, null=True)),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('admin_remarks', models.CharField(blank=True, max_length=255, null=True)),
                ('updation_date', models.DateField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Volunteer',
                'db_table': 'charivol_volunteers',
            },
        ),
        migrations.AddField(
            model_name='donation',
            name='volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='charivol.volunteer'),
        ),
    ]
