# Generated by Django 5.2.1 on 2025-06-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charivol', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationarea',
            name='area_postal_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
