# Generated by Django 5.2.1 on 2025-06-10 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charivol', '0003_donation_volunteer_remarks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='donation',
            old_name='donation_user',
            new_name='donatur',
        ),
    ]
