# Generated by Django 5.2.1 on 2025-07-14 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charivol', '0004_rename_donation_user_donation_donatur'),
    ]

    operations = [
        migrations.AddField(
            model_name='donationarea',
            name='donation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='charivol.donation'),
        ),
    ]
